### ISSUE TITLE
How to get SnowKITTI ？

### ISSUE THREAD

**Issue by dinghuixiang-github** [alvariseppanen/4DenoiseNet#5]
Hello ,thank you for your great work,
I have seen the simulation model in https://github.com/SysCV/LiDAR_snow_sim. A question is that point cloud in KITTI has 4 channels(x,y,z, intensity)，the simulation model is used for STF which has 5 channels. Could you please tell me how can we change the code to match the KITTI dataset. Hoping for your reply.

**Comment by alvariseppanen** [comment]
Hello, 

You can download SnowyKITTI here: https://www.dropbox.com/s/o3r654cdzfl405d/snowyKITTI.zip?dl=0

The fifth channel is for laser elevation angle. Since KITTI does not include that, you have to compute those yourself e.g. project the point cloud and use the row indices.

If you plan to use our work, please cite us. 
Citation is coming soon, accepted by IEEE Robotics and Automation Letters.

Best regards, 
Alvari
